apiVersion: apps/v1
kind: Deployment
metadata:
  name: daksh-deployment
  labels:
    app: daksh
spec:
  selector:
    matchLabels:
      env: production
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        env: production
    spec:
      containers:
        - name: nginx
          image: nginx
